### ISSUE TITLE
Suggestion: Tough as Nails Compatability

### ISSUE THREAD

**Issue by DrDarkfire** [KurodaAkira/RPG-Hud#15]
I love this mod, I love tough as nails, but if I want to use all this mod has to offer. TaN looks way out of place. Is it possible for you to have that kind of integration so I don't have the TaN stuff looking out of place?

**Comment by Raelzaryn** [comment]
This is mod compatiblitly and while important I don't have the time to look into how to make mods compatible at all. Once I have more time on my hands and have finished the priority features (resizing and element moving) I'll look into it.

**Comment by MagmaSlime123** [comment]
Its been 3 years.

**Comment by Raelzaryn** [comment]
during most of the time I didnt actively mod minecraft nor play it.
On another note. this issue is due to TAN using the wrong render events to render it's overlay (it uses .AIR for thirst despite thirst not actually doing anything with air and .PORTAL and .EXPERIENCE for temperate. again neither of which it actually uses). Working around this on my end would be very tough and according to the forge devs, this is a bug with TAN (they should use .ALL instead).
