### ISSUE TITLE
Config directory named incorrectly

### ISSUE THREAD

**Issue by austragus** [KurodaAkira/RPG-Hud#22]
The config directory is set as "minecraft\config\RPG-HUD" instead of "minecraft/config/RPG-HUD"

**Comment by Raelzaryn** [comment]
I don't know how it is for you but for me it only works that way.

**Comment by XvSkItZvX** [comment]
I can't say for sure because I don't have a great deal of experience on Linux/Unix system. I believe though that is one of the differences between Windows and Linux/Unix OS's. It's not much help if any at all, but perhaps some insight into why this is an issue. Honestly just a pleb trying to be useful lol..

**Comment by Raelzaryn** [comment]
I'll read some stuff about it. maybe I can figure it out :)
Thanks for letting me know

**Comment by XvSkItZvX** [comment]
Yay, glad to help...though given my uncertainty I hope that @austragus will confirm his OS to see if my statement is even relevant.

**Comment by Raelzaryn** [comment]
I've done a bit of reading and '\' seems to be specific for windows. '/' should work for every platform. Dunno why it didn't work for me previously but I've changed it and now it works.

**Comment by XvSkItZvX** [comment]
gotcha, it wasn't exactly the direction of the /, but the quote types used...good to know.

**Comment by Raelzaryn** [comment]
nah I used the ' ' to highlight the symbol.
previoulsy the path was set to ".\config\RPG-HUD\settings.cfg" now it's "./config/RPG-HUD/settings.cfg"

**Comment by XvSkItZvX** [comment]
ahh ok...lol...
