### ISSUE TITLE
[1.12.2] Vanilla Health Bar

### ISSUE THREAD

**Issue by TrialDragon** [KurodaAkira/RPG-Hud#43]
When I play using this mod I have only the vanilla health bar no matter what I do even if I force render rpg hud bar. I will include the modlist and while they are not currently in the mod file I also use tinkers construct and tinkers leveling.
![2018-02-19_18 42 41](https://user-images.githubusercontent.com/31419708/36405770-2b337652-15a7-11e8-8759-21e733309fa3.png)
<img width="766" alt="mods list" src="https://user-images.githubusercontent.com/31419708/36405774-31bd37c4-15a7-11e8-8338-3b94d2105727.PNG">

**Comment by RiokuMattenake** [comment]
This is caused by mantle.

Find this in the config of this mod:
` # Prevent the render event of this element. This might disable features of other mods.   §cActivate this if another mod renders §csomething you don't want §cand can't disable it otherwise §cWARNING: Might disable other things, too
    `B:prevent_event_health=false`

and set false to true. This should fix your issue.
