### ISSUE TITLE
Compatibility Issue with AvatarMod 2: Out of the Iceberg

### ISSUE THREAD

**Issue by FavouriteDragon** [KurodaAkira/RPG-Hud#55]
For some reason, RPGHUD completely eliminates all of the mod's HUD. I'm just curious on how to fix this: currently, the mod hooks into the experience ElementType for rendering and hooks into RenderGameOverlayEvent.Post. How should I change it so it doesn't conflict with your mod?

**Comment by sor1n** [comment]
Hi there, there are more in-depth settings in RPG-HUD regarding the experience bar, that should allow for things like: preventing the mod from overtaking it, keeping it to render the normal Minecraft way. Have you tried messing with the config settings to see if anything works?

**Comment by Raelzaryn** [comment]
the problem with hooking into the experience is the mod (as of 3.7) also hooks into it and needs to cancel it to prevent the vanilla one from rendering. They should instead hook into the "ALL" type for hud rendering in order not to conflict.
Prior to 3.7 you could try messing with the debug settings for experience in order to have the client render both.
As such this isn't an issue I can fix on this end.
